### ISSUE TITLE
Canceled Error?

### ISSUE THREAD

**Issue by Kayxue** [JoseLion/rxjs-axios#41] opened 2024-04-25 03:34 UTC
I wrote the code below and try to get data from an api repeatedly with interval
```ts
import { axios } from "rxjs-axios";
import { map, repeat } from "rxjs";

axios
    .get("",{responseType:"text"})
    .pipe(map(({data}) => data),repeat({delay:5000}))
    .subscribe(data => {
        console.log(data)
    });
```
First time it successfully got the data, but for the second time it printed out "CanceledError: canceled", what does it mean? It won't send request to the api again?

**Comment by JoseLion** [comment] 2024-06-23 05:44
@Kayxue, sorry for the late response. Unfortunately, I missed the notification.

Thanks for the report! I was able to reproduce the issue. The problem is that all the requests currently share the same abort signal, so the second request is also marked as canceled when the first observable is torn down. I found a way to create an independent signal for each observable. I'll push a fix shortly and make a new release as soon as possible 🙂

**Closed** 2024-06-23 06:51 UTC
